### ISSUE TITLE
amplification attack dnsmasq-pi-hole

### ISSUE THREAD

**Issue by tkima** [simonwep/openvpn-pihole#2]
The docker works just out of the box. That is really nice. 
But the current installation is vulnerable for amplification attack trough dnsmasq-pi-hole on port 53. 

A semi fix could be to add ratelimit to port 53 trough iptables:
iptables -A INPUT -p udp --dport 53 -m string --from 40 --algo bm --hex-string '|0000FF0001|' -m recent --set --name dnsanyquery 
iptables -A INPUT -p udp --dport 53 -m string --from 40 --algo bm --hex-string '|0000FF0001|' -m recent --name dnsanyquery --rcheck --seconds 60 --hitcount 3 -j DROP
iptables -A INPUT -p tcp --dport 53 -m string --from 52 --algo bm --hex-string '|0000FF0001|' -m recent --set --name dnsanyquery 
iptables -A INPUT -p tcp --dport 53 -m string --from 52 --algo bm --hex-string '|0000FF0001|' -m recent --name dnsanyquery --rcheck --seconds 60 --hitcount 3 -j DROP

Or just remove the open port 53 & 67 in docker? Because it aready depends on openvpn. 
        depends_on:
            - "openvpn"
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"

The ads still won't show and keeps the dns hidden trough https://www.dnsleaktest.com

Greets

**Comment by simonwep** [comment]
Thank you for the report, sorry for coming back to it _quite_ late 😅
